# Generated by Django 4.2.6 on 2023-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('personality', models.CharField(choices=[('', 'Enter your personality'), ('Am soo Quity', 'Am soo Quity'), ('Am talkative', 'Am talkative'), ('Am moderate', 'Am moderate')], default='Am talkative', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7)),
                ('experience', models.BooleanField(default=False)),
                ('smoker', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('situation', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('woooo', 'woooo'), ('zeeeee', 'zeeeee')], default='pending', max_length=8)),
                ('job', models.CharField(default='Developing', max_length=50)),
                ('messag', models.TextField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
