# Generated by Django 4.2.6 on 2023-10-10 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.CharField(choices=[('Less to 300,000', 'Less to 300,000'), ('Is between 300,000 and 700,000', 'Is between 300,000 and 700,000'), ('Is between 700,000 and 1,000,000', 'Is between 700,000 and 1,000,000'), ('It greater to 1,000,000', 'It greater to 1,000,000')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
