# Generated by Django 4.2.6 on 2023-10-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_candidate_salary_alter_candidate_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('', 'Enter your personality'), ('Am soo Quity', 'Am soo Quity'), ('Am talkative', 'Am talkative'), ('Am moderate', 'Am moderate')], max_length=50),
        ),
    ]
