# Generated by Django 4.2.6 on 2023-10-11 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_candidate_gender_alter_candidate_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents'),
            preserve_default=False,
        ),
    ]
