# Generated by Django 4.2.6 on 2023-10-12 08:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_candidate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('Postgre', 'Postgre'), ('MongoDB', 'MongoDB'), ('MariaDB', 'MariaDB'), ('Others', 'Others')], default='', max_length=43, validators=[0]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Laravel', 'Laravel'), ('Flask', 'Flask'), ('Bootspring', 'Bootspring'), ('Vue', 'Vue'), ('Others', 'Others')], default='', max_length=42, validators=[0]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Php', 'Php'), ('Javascript', 'Javascript'), ('Ruby', 'Ruby'), ('C++', 'C++'), ('Others', 'Others')], default='', max_length=37, validators=[0]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'MySQL'), ('Jquery', 'Jquery'), ('React', 'React'), ('Chart.js', 'Chart'), ('Gsap', 'Gsap'), ('Others', 'Others')], default='', max_length=38, validators=[0]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Xamarin', 'Xamarin'), ('Ionic', 'Ionic'), ('Others', 'Others')], default='', max_length=46, validators=[0]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'React native'), ('SQL', 'SQL'), ('GIT', 'GIT'), ('Docker', 'Docker'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], default='', max_length=33, validators=[0]),
        ),
    ]
