# Generated by Django 5.0.4 on 2024-05-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_candidate_databases_candidate_frameworks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='databases',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='others',
        ),
    ]
